### ISSUE TITLE
Feature request: add boringssl support

### ISSUE THREAD

**Issue by yzabalotski** [aws/aws-sdk-cpp#1241]
Hi, it would be nice to have a possibility to link with boringssl instead of openssl :)

**Comment by KaibaLopez** [comment]
Hi @yzabalotski,
boringssl is not really  supported in our sdk, but it should be compatible, see here for reference:  #1208

**Comment by eakraly** [comment]
@KaibaLopez Closing the ticket without any valuable response is not the best response to a developer.
You did not provide any explanation, nor reference to roadmap - nothing.
I do not see how pointing at #1208 is a meaningful response.
If anything you should have pointed to #1206 which is a relevant discussion but the problem is still not solved.

**Comment by JonathanHenson** [comment]
If you build libcurl against boringssl and put the boringssl artifacts in your cmake_prefix_path, it should just work since boringssl is openssl compatible. I’m assuming from the existence of the question, this didn’t work for you? Could you share further details?

**Comment by eakraly** [comment]
Thanks @JonathanHenson !

Ubuntu 18.04
gcc 7.4
boringssl latest master

cmake command used:
`cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/boringssl -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="transcribe" .
make`

The error part of build:
`In file included from /tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:22:0:
/usr/local/opt/boringssl/include/openssl/sha.h:113:5: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]
     };
     ^
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In function 'void Aws::Utils::Crypto::OpenSSL::init_static_state()':
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:62:41: error: 'OPENSSL_INIT_LOAD_CRYPTO_STRINGS' was not declared in this scope
                     OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS /*options*/ ,NULL /* OpenSSL init settings*/ );
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:62:41: note: suggested alternative: 'OPENSSL_INIT_SETTINGS'
                     OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS /*options*/ ,NULL /* OpenSSL init settings*/ );
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         OPENSSL_INIT_SETTINGS
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:62:21: error: 'OPENSSL_init_crypto' was not declared in this scope
                     OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS /*options*/ ,NULL /* OpenSSL init settings*/ );
                     ^~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:64:21: error: 'OPENSSL_add_all_algorithms_noconf' was not declared in this scope
                     OPENSSL_add_all_algorithms_noconf();
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:64:21: note: suggested alternative: 'OPENSSL_add_all_algorithms_conf'
                     OPENSSL_add_all_algorithms_noconf();
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     OPENSSL_add_all_algorithms_conf
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function 'virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::MD5OpenSSLImpl::Calculate(const String&)':
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:158:43: error: 'EVP_MD_CTX_FLAG_NON_FIPS_ALLOW' was not declared in this scope
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:158:43: note: suggested alternative: 'EVP_CIPHER_CTX_FLAG_WRAP_ALLOW'
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                           EVP_CIPHER_CTX_FLAG_WRAP_ALLOW
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:158:17: error: 'EVP_MD_CTX_set_flags' was not declared in this scope
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                 ^~~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:158:17: note: suggested alternative: 'EVP_MD_meth_get_flags'
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                 ^~~~~~~~~~~~~~~~~~~~
                 EVP_MD_meth_get_flags
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp: In member function 'virtual Aws::Utils::Crypto::HashResult Aws::Utils::Crypto::MD5OpenSSLImpl::Calculate(Aws::IStream&)':
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:172:43: error: 'EVP_MD_CTX_FLAG_NON_FIPS_ALLOW' was not declared in this scope
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:172:43: note: suggested alternative: 'EVP_CIPHER_CTX_FLAG_WRAP_ALLOW'
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                           EVP_CIPHER_CTX_FLAG_WRAP_ALLOW
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:172:17: error: 'EVP_MD_CTX_set_flags' was not declared in this scope
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                 ^~~~~~~~~~~~~~~~~~~~
/tmp/hpstuff/aws-sdk-cpp/aws-sdk-cpp-1.7.185/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:172:17: note: suggested alternative: 'EVP_MD_meth_get_flags'
                 EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
                 ^~~~~~~~~~~~~~~~~~~~
                 EVP_MD_meth_get_flags
cc1plus: all warnings being treated as errors`

**Comment by JonathanHenson** [comment]
I know this isn’t the best answer but this looks like a boringssl problem. The openssl compatible headers are supposed to be c++ compatible but there’s c99 features in them. From an idealistic perspective I’d say we should fix that. From a practical perspective I’m unsure if that will be viable. What do you think we should do here?

**Comment by Ri0n** [comment]
Hi 
Seems like for gcc anonymous struct warning can be suppressed with `-fms-extensions` and for clang with `-Wno-c11-extensions`.

Besides AFAIK it's not fully ABI compatible, but required changes are minor.

Anyway it would be nice to have to BoringSSL support since some products rely on it, especially Google's ones. And it's where we have a choice like either to fix AWS SDK or fully migrate to alternative Google solutions.

Regards.

**Comment by JonathanHenson** [comment]
Some of these fixes need to be made regardless... agreed. I’ll work with the team and see what we come up with.

**Comment by KaibaLopez** [comment]
Sorry for the premature closure of the issue, and will try to be better at that for sure.
Also, my bad on the issue I linked, that was a typo I did mean to link 1206, which as you say was not resolved in the "we now fully support it" sense, but with the changes we made at the time, boringssl should be compatible. 
I closed the issue based on the idea that there was no action for us, but in the future I'll try to give proper time for discussion.
