### ISSUE TITLE
TransferClient: missing CancelDownload implementation

### ISSUE THREAD

**Issue by renatoaf** [aws/aws-sdk-cpp#259]
TransferClient.h declares:

        void CancelDownload(std::shared_ptr<DownloadFileRequest>& fileRequest) const;

but there is no implementation for it on TransferClient.cpp

       https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-transfer/source/transfer/TransferClient.cpp

I'm also experiencing problems with getProgress method (always returning 0.0) on DownloadFileRequest, but I'll dig a little bit more into the problem first.

Thanks.

**Comment by mattman71** [comment]
Me too. I'm trying to fix a problem where my user cancels a download, but I'm having trouble finding a way to stop the download thread. Even if I bail out of my WaitForDownloadAndUpdate, then transferclient gleefully continues downloading. Same as @renatoaf, I found the CancelDownload() method, but there's no implementation for it -- I just get an unresolved external.

Any help for how to properly cancel and kill a download thread for a cancel scenario?

**Comment by renatoaf** [comment]
I haven't tried it yet, but I guess a workaround would be to implement your own Aws::Threading::Executor with a proper mechanism to terminate running threads (default executor simply creates a thread and detaches it) and configure it on ClientConfiguration. Not sure though if it is safe to terminate AWS download thread.

**Comment by JonathanHenson** [comment]
I'd hold on. I'm rewriting the whole thing, I hope to have it out later this week.

**Comment by JonathanHenson** [comment]
This is currently being reviewed internally, but I'd love your thoughts while we're at it:

https://s3.amazonaws.com/aws-sdk-cpp-demos/transferRewrite.diff

Notes:

Deleted TransferClient and everything related to it. Added a simpler interface, TransferManager. TransferHandle is the other half of the control interface which is what the user would use to control their transfers. I added a few utilities to core to support the changes. Largely a generic queue locker, and a std::stream_buf that runs off of a preallocated buffer.

Later I'll be adding parallel downloads (harder to pull off), and directory synchronization, but this has feature parity with the original TransferClient.

Major performance differences:
All stream memory is preallocated (so no more allocation during the transfer)
Threading model is simplified.
No busy waits

Things I'm not happy about:
Mutex heavy
I discovered that we aren't handling Http/Continue correctly on Windows while testing. however, this isn't a regression from the previous code base so I'll add it to the backlog.
For multi-part uploads, we only update the transfer progress for each part because it was too complicated to back out updates if a part fails.

Testing notes:
all unit tests, and integration tests pass.
Uploads saturate the nic (which was my goal)
Downloads, since they aren't in parallel, still need work from a performance standpoint.

**Comment by JonathanHenson** [comment]
I added a branch TransferRewrite for you to experiment with and give feedback before I push it to master.

**Comment by mattman71** [comment]
Thanks Jonathan. I got a build failure from ResourceManager.h. It doesn't know what pop(), push(), and assert() are. I'm using Visual Studio 2015 for an x64 debug build. My system knows about pop_back(), push_back(). so I swapped those out. I'm not sure what the assert() is for on line 54, but I tried swapping that out with _ASSERT(). After all that, I'm not having any luck getting tests to run. Not sure if it's related to those substitutions or not. I just wanted to see the TransferManager_BigTest in action.

Test Name:	TransferTests.TransferManager_BigTest
Test FullName:	TransferTests.TransferManager_BigTest
Test Source:	c:\prog\aws-sdk-cpp\aws-cpp-sdk-transfer-tests\transfertests.cpp : line 571
Test Outcome:	Failed
Test Duration:	0:00:18.378

Result Message:	C:\PROG\aws-sdk-cpp\aws-cpp-sdk-transfer-tests\TransferTests.cpp:608
Value of: requestPtr->GetMultiPartId().empty()
  Actual: true
Expected: false

unknown file
SEH exception with code 0xc0000005 thrown in the test body.

**Comment by JonathanHenson** [comment]
I may have accidentally pushed some in progress updates out. Can you revert to a commit from more than two days ago?

**Comment by JonathanHenson** [comment]
Ok, sorry about that. I most certainly did accidentally push out on-going changes. I've just pushed out my latest revision, which builds and the tests pass for on my local machine. Give it a try and let me know what you think.

**Comment by JonathanHenson** [comment]
Cancel() is now available on TransferHandle from the TransferManager().

**Comment by mattman71** [comment]
The cancel takes several seconds, but is certainly workable, and much better than not having a cancel at all. Much thanks!

**Comment by future1122** [comment]
Hi  , @JonathanHenson 
I call the Cancel() method  in TransferHandler.    sometimes it  block at the  WaitUntilFinished() for several seconds  and cancel the download, but sometime it block even servral minutes and still cannot cancel the download.
If you have an ideas about the problem.please give some advice 
 thanks.
